# Generated by Django 3.2.7 on 2021-09-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='character',
        ),
        migrations.AddField(
            model_name='favourites',
            name='birth',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='favourites',
            name='death',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='favourites',
            name='gender',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='favourites',
            name='hair',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='favourites',
            name='height',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='favourites',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='favourites',
            name='race',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='favourites',
            name='realm',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='favourites',
            name='spouse',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='favourites',
            name='wikiUrl',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
