# Generated by Django 3.2.7 on 2021-09-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_favourites_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='birth',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='death',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='gender',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='hair',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='height',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='race',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='realm',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='spouse',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='wikiUrl',
            field=models.CharField(default='', max_length=500),
        ),
    ]
