# Generated by Django 3.2.7 on 2021-09-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210917_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='character_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
