# Generated by Django 3.2.7 on 2021-09-17 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_favourites_character_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='character_id',
            new_name='_id',
        ),
    ]
