# Generated by Django 3.2.7 on 2021-09-17 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_rename_character_id_favourites__id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(default='', max_length=500)),
                ('dialog', models.CharField(default='', max_length=500)),
                ('movie', models.CharField(default='', max_length=500)),
                ('character', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
