# Generated by Django 3.2.7 on 2021-09-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_favouritequotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritequotes',
            name='character',
            field=models.CharField(default='', max_length=500),
        ),
    ]
