# Generated by Django 3.2.7 on 2021-09-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_favouritequotes_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritequotes',
            name='_id',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
