# Generated by Django 3.2.7 on 2021-09-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_favouritequotes__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='_id',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
