# Generated by Django 3.2.7 on 2021-09-17 04:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_alter_favourites__id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourites',
            new_name='FavouriteCharacters',
        ),
    ]
